name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify your Node.js version

    - name: Install dependencies
      run: |
        npm install
        npm install -g vercel  # Install Vercel CLI

    - name: Deploy to Vercel
      id: deploy
      run: |
        DEPLOYMENT_URL=$(vercel --prod --confirm --token ${{ secrets.VERCEL_TOKEN }} | grep "https://" | awk '{print $1}')
        echo "Deployment URL: $DEPLOYMENT_URL"
        echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV

    - name: Add Custom Subdomain to Vercel
      run: |
        curl -X POST "https://api.vercel.com/v9/projects/${{ secrets.VERCEL_PROJECT_ID }}/domains" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "name": "${{ secrets.SUBDOMAIN }}.manishmoneymanage.tech"
          }'

    - name: Assign Subdomain to Deployment
      run: |
        curl -X PATCH "https://api.vercel.com/v2/domains/${{ secrets.SUBDOMAIN }}.manishmoneymanage.tech" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "project": "${{ secrets.VERCEL_PROJECT_ID }}"
          }'

    - name: Output Deployment URL with Subdomain
      run: |
        echo "Subdomain URL: https://${{ secrets.SUBDOMAIN }}.manishmoneymanage.tech"
